DeveloperblogWebsite/Models/DeveloperBlogModels/PostModels/PostViewModel.cs
using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeveloperblogWebsite.Models.DeveloperBlogModels.PostModels {
    public class PostViewModel:PostListedModel {

        public virtual List<ImageModel> Images { get; set; }
        public virtual List<CommentListModel> Comments { get; set; }
        public CommentInsertModel CommentInsert { get; set; }

        public PostViewModel() {
            CommentInsert = new CommentInsertModel() { PostID = ID};
        }
        /*
        public PostViewModel(PostEntity entity):base(entity) {

            Images = new List<ImageModel>();
            Comments = new List<CommentListModel>();

            foreach (ImageEntity image in entity.Images) {
                Images.Add(new ImageModel(image));
            }

            foreach (CommentEntity comment in entity.Comments) {
                Comments.Add(new CommentListModel(comment));
            }
        }
        */
    }
}

DeveloperblogWebsite/Models/DeveloperBlogModels/PostViewModel.cs
using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeveloperblogWebsite.Models.DeveloperBlogModels {
    public class PostViewModel:PostListModel {

        public virtual List<ImageModel> Images { get; set; }
        public virtual List<CommentListModel> Comments { get; set; }
        public CommentInsertModel CommentInsert { get; set; }

        public PostViewModel() {
            CommentInsert = new CommentInsertModel() { PostID = ID};
        }
        /*
        public PostViewModel(PostEntity entity):base(entity) {

            Images = new List<ImageModel>();
            Comments = new List<CommentListModel>();

            foreach (ImageEntity image in entity.Images) {
                Images.Add(new ImageModel(image));
            }

            foreach (CommentEntity comment in entity.Comments) {
                Comments.Add(new CommentListModel(comment));
            }
        }
        */
    }
}

DeveloperblogWebsite/Controllers/CommentController.cs
using DeveloperblogWebsite.Helpers;
using DeveloperblogWebsite.Models.DeveloperBlogModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DeveloperblogWebsite.Controllers
{
    public class CommentController : Controller
    {
        private readonly string COMMENT_URL = "/Comment";

        [HttpPost]
        public async Task<ActionResult> Create(CommentInsertModel model) {
            model.Author = "DeathToAllPigeons";
            if (ModelState.IsValid) {
                var content = JsonConvert.SerializeObject(model, Formatting.Indented);
                HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(COMMENT_URL + "/Save", new StringContent(content), " ");
            }

            return RedirectToAction("Details", "Post", new { ID = model.PostID });
        }

        public async Task<ActionResult> Edit(int id) {
            try {
                CommentInsertModel comment;
                HttpResponseMessage responseMessage = await HttpHelper.GetResponsetMassage(COMMENT_URL + "/" + id, "");
                if (responseMessage.IsSuccessStatusCode) {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                    comment = JsonConvert.DeserializeObject<CommentInsertModel>(responseData);
                    return View(comment);
                }
                return HttpNotFound();
            }
            catch (Exception) {
                return HttpNotFound();
            }
        }


        [HttpPost]
        public async Task<ActionResult> Edit(CommentInsertModel model) {
            if (ModelState.IsValid) {
                var content = JsonConvert.SerializeObject(model, Formatting.Indented);
                HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(COMMENT_URL + "/Save", new StringContent(content), "");
                if (responseMessage.IsSuccessStatusCode) {
                    return RedirectToAction("Details", "Post", new { ID = model.PostID });
                }
                else {
                    return View(model);
                }
            }
            else {
                return View(model);
            }
        }

        public async Task<ActionResult> Delete(int id, int postId) {
            HttpResponseMessage responseMessage = await HttpHelper.DeleteResponsetMassage(COMMENT_URL + "/Delete/" + id, "");
            if (responseMessage.IsSuccessStatusCode) {
                return RedirectToAction("Details", "Post", new { ID = postId }) ;
            }
            else return HttpNotFound();
        }

        public async Task<ActionResult> Respond(int responseToID) {
            CommentListModel responceTo;
            HttpResponseMessage responseMessage = await HttpHelper.GetResponsetMassage(COMMENT_URL + "/" + responseToID, "");
            if (responseMessage.IsSuccessStatusCode) {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                responceTo = JsonConvert.DeserializeObject<CommentListModel>(responseData);
                CommentResponceModel responce = new CommentResponceModel() { ResponceTo = responceTo, PostID = responceTo.PostID };
                if(responceTo.ResponseToID!=null && responceTo.ResponseToID > 0) {
                    responce.ResponseToID = responceTo.ResponseToID;
                }
                else {
                    responce.ResponseToID = responceTo.ID;
                }

                return View(responce);
            }
            else {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Respond(CommentResponceModel responce) {
            responce.Author = "DeathToAllPigeons";
            if (ModelState.IsValid) {
                var content = JsonConvert.SerializeObject(responce, Formatting.Indented);
                HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(COMMENT_URL + "/Save", new StringContent(content), " ");
            }

            return RedirectToAction("Details", "Post", new { ID = responce.PostID });
        }
    }
}

DeveloperblogWebsite/Controllers/PostController.cs
using DeveloperblogWebsite.Helpers;
using DeveloperblogWebsite.Models.DeveloperBlogModels;
using DeveloperblogWebsite.Models.DeveloperBlogModels.PostModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DeveloperblogWebsite.Controllers
{
    public class PostController : Controller
    {
        private readonly string POST_URL = "/Post";

        // GET: Post
        public async Task<ActionResult> Index(int page = 1, int pageSize = 10, bool descending = true, string sortParameter = "Date") {
            PagerModel pager = new PagerModel() { Page = page, PageSize = pageSize, Desending = descending, SortParameter = sortParameter };
            var content = JsonConvert.SerializeObject(pager, Formatting.Indented);
            List<PostListedModel> posts = new List<PostListedModel>();
            HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(POST_URL, new StringContent(content),"");
            if (responseMessage.IsSuccessStatusCode) {
               
                var responceData = responseMessage.Content.ReadAsStringAsync().Result;
                posts = JsonConvert.DeserializeObject<List<PostListedModel>>(responceData);
                
            }
            HttpResponseMessage postsCountResponseMessage = await HttpHelper.GetResponsetMassage(POST_URL + "/Count");

            if (postsCountResponseMessage.IsSuccessStatusCode) {
                var responceData = postsCountResponseMessage.Content.ReadAsStringAsync().Result;
                var entityCountData = JsonConvert.DeserializeAnonymousType(responceData, new { entityCount = 0 });
                pager.PagesCount = (int)Math.Ceiling(entityCountData.entityCount / (double)pageSize);
            }
            return View(new PostListingModel(pager,posts));
        }

        public ActionResult Create() {
            return View();
        }

        public async Task<ActionResult> Details(int id) {
            HttpResponseMessage responseMessage = await HttpHelper.GetResponsetMassage(POST_URL +"/"+ id, "");
            if (responseMessage.IsSuccessStatusCode) {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                PostViewModel post = JsonConvert.DeserializeObject<PostViewModel>(responseData);
                post.CommentInsert = new CommentInsertModel() { PostID = post.ID};                
                return View(post);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Create(PostInsertModel model) {
            model.Author = "DeathToAllPigeons";
            if (ModelState.IsValid) {
                var content = JsonConvert.SerializeObject(model, Formatting.Indented);
                HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(POST_URL+"/Save", new StringContent(content), " ");
                if (responseMessage.IsSuccessStatusCode) {
                    return RedirectToAction("Index");
                }
                else {
                    return View();
                }
            }
            else {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id) {
            try {
                PostInsertModel post;
                HttpResponseMessage responseMessage = await HttpHelper.GetResponsetMassage(POST_URL + "/" + id, "");
                if (responseMessage.IsSuccessStatusCode) {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                    post = JsonConvert.DeserializeObject<PostInsertModel>(responseData);
                    return View(post);
                }
                return HttpNotFound();
            }
            catch (Exception) {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(PostInsertModel model) {
            if (ModelState.IsValid) {
                var content = JsonConvert.SerializeObject(model, Formatting.Indented);
                HttpResponseMessage responseMessage = await HttpHelper.PostResponsetMassage(POST_URL+"/Save", new StringContent(content), "");
                if (responseMessage.IsSuccessStatusCode) {
                    return RedirectToAction("Details", new { id=model.ID});
                }
                else {
                    return View(model);
                }
            }
            else {
                return View(model);
            }
        }

        public async Task<ActionResult> Delete(int id) {
            HttpResponseMessage responseMessage = await HttpHelper.DeleteResponsetMassage(POST_URL + "/Delete/" + id, "");
            if (responseMessage.IsSuccessStatusCode) {
                return RedirectToAction("Index");
            }
            else return HttpNotFound();
        }
    }
}

DeveloperblogWebsite/Views/Post/Create.cshtml
@model DeveloperblogWebsite.Models.DeveloperBlogModels.PostInsertModel

@{
    ViewBag.Title = "Create Post";
}

<h2>Create Post</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PostInsertModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @rows = "30" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeveloperblogWebsite/Views/Post/Details.cshtml
@model DeveloperblogWebsite.Models.DeveloperBlogModels.PostViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PostViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimePosted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimePosted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>
        
        @Html.Partial("../Image/_Upload", new DeveloperblogWebsite.Models.DeveloperBlogModels.ImageModel() { PostID = Model.ID })

    </dl>
</div>
<div class="row">
    @foreach (DeveloperblogWebsite.Models.DeveloperBlogModels.ImageModel image in Model.Images) {
        @Html.Partial("../Image/_Display", image)
    }
</div>
<div>
    @Html.Partial("../Comment/_CommentSection", Model.Comments)
</div>
    @using (Html.BeginForm("Create", "Comment",FormMethod.Post)) {
        @Html.Partial("../Comment/_Create", Model.CommentInsert)
    }
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DeveloperblogWebsite/Views/Post/Edit.cshtml
@model DeveloperblogWebsite.Models.DeveloperBlogModels.PostInsertModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PostInsertModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID, new { id = "natureOfVisitField" })
        @Html.HiddenFor(model => model.Author, new { id = "natureOfVisitField" })
        @Html.HiddenFor(model => model.TimePosted, new { id = "natureOfVisitField" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @rows = "30" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeveloperblogWebsite/Views/Post/Index.cshtml
@model DeveloperblogWebsite.Models.DeveloperBlogModels.PostModels.PostListingModel

@{
    ViewBag.Title = "Posts";
}

<h2>Posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            Title
            <b>@Html.ActionLink("^", "Index", new { page = Model.Pager.Page, pageSize = Model.Pager.PageSize, descending = false, sortParameter = "Title" })</b>
            @Html.ActionLink("v", "Index", new { page = Model.Pager.Page, descending = true, sortParameter = "Title" })
        </th>
        <th>
            Author
            <b>@Html.ActionLink("^", "Index", new { page = Model.Pager.Page, pageSize = Model.Pager.PageSize, descending = false, sortParameter = "Author" })</b>
            @Html.ActionLink("v", "Index", new { page = Model.Pager.Page, descending = true, sortParameter = "Author" })
        </th>
        <th>
            Posted on
            <b>@Html.ActionLink("^", "Index", new { page = Model.Pager.Page, pageSize = Model.Pager.PageSize, descending = false, sortParameter = "Date" })</b>
            @Html.ActionLink("v", "Index", new { page = Model.Pager.Page, descending = true, sortParameter = "Date" })
        </th>
        <th>
            Views
            <b>@Html.ActionLink("^", "Index", new { page = Model.Pager.Page, pageSize = Model.Pager.PageSize, descending = false, sortParameter = "Views" })</b>
            @Html.ActionLink("v", "Index", new { page = Model.Pager.Page, pageSize = Model.Pager.PageSize, descending = true, sortParameter = "Views" })
        </th>
        <th>
            Page Size: 
            @Html.ActionLink("1", "Index", new { page = Model.Pager.Page, pageSize = 1, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })
            @Html.ActionLink("5", "Index", new { page = Model.Pager.Page, pageSize = 5, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })
            @Html.ActionLink("10", "Index", new { page = Model.Pager.Page, pageSize = 10, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })
        </th>
    </tr>

    @foreach (var item in Model.Items) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimePosted)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Views)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

@{
    if (Model.Pager.Page > 1) { <b>@Html.ActionLink("<", "Index", new { page = Model.Pager.Page - 1, pageSize = Model.Pager.PageSize, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })</b>}
    for (int i = 1; i <= Model.Pager.PagesCount; i++) {
        <b>@Html.ActionLink(i.ToString(), "Index", new { page = i, pageSize = Model.Pager.PageSize, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })</b>
    }
    if (Model.Pager.Page < Model.Pager.PagesCount) { <b>@Html.ActionLink(">", "Index", new { page = Model.Pager.Page + 1, pageSize = Model.Pager.PageSize, descending = Model.Pager.Desending, sortParameter = Model.Pager.SortParameter })</b>}
}